safe:        false
baseurl:     /
url: http://localhost:4000

name: Graeme Arthur
description:  Random hard worker who lives and works in the UK
url: http://rthur.me
domain: blog.rthur.me
commentlinks: true
twitter-username: graemearthur
feedburnerurl: http://feeds.feedburner.com/graemearthur
google-analytics-tracking-id: UA-29363864-1

source:      .
destination: ./_site
plugins:     ./_plugins
paginate_path: 'blog/page:num'

future:      true
lsi:         false
pygments:    false
markdown:    maruku
permalink:   /:title/
paginate: 5

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

excerpt_separator: "<!-- more -->"