safe:        false
baseurl:     "https://rthur.me/"
url: https://rthur.me

name: Graeme Arthur
description:  Random hard worker who lives and works in the UK
url: https://rthur.me
domain: rthur.me
commentlinks: true
twitter-username: graemearthur
feedburnerurl: http://feeds.feedburner.com/graemearthur
google-analytics-tracking-id: UA-29363864-1

source:      .
destination: ./_site
plugins_dir:   ./_plugins
paginate_path: 'blog/page:num'

future:      true
lsi:         false
highlighter:    null
markdown:    kramdown
permalink:   /:title/
paginate: 5

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

excerpt_separator: "<!-- more -->"
root: /
